### ISSUE TITLE
[FEATURE] Permit to install files from salt fileserver instead of getting content in pillar

### ISSUE THREAD

**Issue by baby-gnu** [saltstack-formulas/exim-formula#17]
### Is your feature request related to a problem?

I need to tweak my exim configure to:

- use a [smarthost with authentication](https://wiki.debian.org/Exim#Smarthost_with_Authentication) 
- force the connection [to be SMTPS (it does not support STARTTLS)](https://wiki.debian.org/Exim#Communicating_with_a_smarthost)

I need to:

1. Create `/etc/exim4/exim4.conf.localmacros` with proper macro definitions
2. Create `/etc/exim4/passwd.client`

### Describe the solution you'd like

I think that the [current handling of extra configuration files](https://github.com/saltstack-formulas/exim-formula/blob/v0.6.1/exim/config/file.sls#L26) could be extended or modified to lookup files as template from the salt fileserver instead of the pillar.

As an example of what I'm thinking:

``` sls
{%- set extra_files = salt['config.get']('exim:extra_files')
{%- if extra_files %}
{%-   for filename, params in extra_files.items() %}
{#-     Use filename as default source name %}
{%-     set sources = params.get('sources', [filename])
{%-     set user = params.get('user', 'root') %}
{%-     set group = params.get('group', 'root') %}
{%-     set mode = params.get('mode, '0644') %}
{%-     set template = params.get('template', None)
{%-     set tofs_lookup = 'exim/config/' ~ filename %}
{{ exim.config_dir }}/{{ filename }}:
  file.managed:
    - name: {{ exim.config_dir | path_join(filename) }}
	- source: {{ files_switch(sources, lookup=tofs_lookup) }}
	- user: {{ user }}
	- group: {{ group }}
	- mode: {{ mode }}
	- makedirs: True
{%      if template %}
	- template: jinja
	- context:
	    exim: {{ exim | json }}
{%- endif %}
	- require:
	  - sls: {{ sls_package_install }}
{%-   endfor %}
{%- endif %}
```

This way I could:

1. Define a pillar like
   ```yaml
   exim:
     extra_files:
	   exim4.conf.localmacros:
	     sources: ['exim4.conf.localmacros.jinja']
		 template: 'jinja'
	   passwd.client:
	     sources: [passwd.client.jinja']
		 user: 'root'
		 group: 'Debian-exim'
		 mode: '0640'
		 template: 'jinja'
   ```
2. Put the template files under `/exim/files/default/` somewhere in the fileserver `files_root`.

NB: templating is parameterised because exim configuration file syntax can be seen interpreted as bogus jinja.

### Describe alternatives you've considered

I think I could use `exim.use_split_config=True` and overwrite files under `/etc/exim4/conf.d/` but the exim syntax can stay in the way of templating.
